image: docker-registry.eccenca.com/eccenca-python:v3.9.14-2
ports:
- port: 8000
tasks:
- before: ./secret_maker.sh docker-registry.eccenca.com ${ECCENCA_DOCKER_REGISTRY_USERNAME} ${ECCENCA_DOCKER_REGISTRY_PASSWORD}
  command: task:check
