---
# https://taskfile.dev

version: '3'

vars:
  PUBLIC_BRANCH: published
  CURRENT_VERSION: 22.1
  MATERIAL_INSIDER_TAG: 8.5.4-insiders-4.24.1
  MATERIAL_TAG: 8.5.4

tasks:

  default:
    summary: |
      List documented tasks
    silent: true
    cmds:
      - task --list

  clean:
    desc: Clean up working directory
    run: once
    cmds:
      - rm -rf site

  install:
    desc: Install needed dependencies
    cmds:
      - poetry install

  check:
    desc: Run complete test suite
    deps:
      - check:links

  check:links:
    desc: Check outgoing links
    deps:
      - install
    cmds:
      - poetry run linkcheckMarkdown -r docs

  build:
    desc: Build the page
    deps:
      - task: install
    cmds:
      - poetry run mkdocs build --strict

  serve:
    desc: Serve the page on localhost
    deps:
      - task: install
    cmds:
      - poetry run mkdocs serve

  use:public:
    desc: switch to public package (non insider)
    cmds:
      - poetry remove mkdocs-material || exit 0
      - poetry add mkdocs-material=={{.MATERIAL_TAG}}
      - poetry update

  use:insider-ssh:
    desc: switch to insider package from github:eccenca via ssh (default)
    cmds:
      - poetry remove mkdocs-material || exit 0
      - poetry add git+ssh://git@github.com:eccenca/mkdocs-material-insiders.git#{{.MATERIAL_INSIDER_TAG}}
      - poetry update

  use:insider-https-token:
    desc: switch to insider package from github:eccenca via token access (build plan)
    cmds:
      - poetry remove mkdocs-material || exit 0
      - poetry add git+https://$GITHUB_TOKEN@github.com/eccenca/mkdocs-material-insiders.git#{{.MATERIAL_INSIDER_TAG}}
      - poetry update

  public:versions:
    desc: List public documentation versions
    deps:
      - task: install
    cmds:
      - poetry run mike list -b {{.PUBLIC_BRANCH}}

  public:deploy:
    desc: Publish the workding directory as version {{.CURRENT_VERSION}}
    deps:
      - task: install
    cmds:
      - >
        poetry run mike deploy -b {{.PUBLIC_BRANCH}}
        --update-aliases {{.CURRENT_VERSION}} latest

  public:serve:
    desc: Start a webserver to manually validate the public branch
    deps:
      - task: install
    cmds:
      - poetry run mike serve -b {{.PUBLIC_BRANCH}}

