"""Test the author list of the print edition's imprint"""
import yaml

from tools.pdf_authors import authors_yaml, next_page, select_authors


def test_most_commits_first_and_ties_by_id_case_insensitive():
    contributors = [
        {"login": "haschek", "contributions": 10, "type": "User"},
        {"login": "seebi", "contributions": 532, "type": "User"},
        {"login": "BorderCloud", "contributions": 10, "type": "User"},
        {"login": "rpietzsch", "contributions": 639, "type": "User"},
    ]
    assert [a["id"] for a in select_authors(contributors)] == ["rpietzsch", "seebi", "BorderCloud", "haschek"]


def test_bots_agents_and_anonymous_contributions_are_not_authors():
    contributors = [
        {"login": "dependabot[bot]", "contributions": 40, "type": "Bot"},
        {"login": "claude-agent", "contributions": 30, "type": "User"},
        {"login": "Codex", "contributions": 20, "type": "User"},
        {"name": "Someone", "email": "someone@example.org", "contributions": 33, "type": "Anonymous"},
        {"login": "sobo", "contributions": 53, "type": "User"},
    ]
    assert select_authors(contributors) == [{"id": "sobo", "commits": 53}]


def test_pagination_follows_the_next_link_only():
    header = (
        '<https://api.github.com/repositories/1/contributors?per_page=100&page=2>; rel="next", '
        '<https://api.github.com/repositories/1/contributors?per_page=100&page=3>; rel="last"'
    )
    assert next_page(header) == "https://api.github.com/repositories/1/contributors?per_page=100&page=2"
    assert next_page("") is None


def test_the_file_names_its_source_and_keeps_the_order():
    text = authors_yaml("eccenca/docs", [{"id": "b", "commits": 2}, {"id": "a", "commits": 1}])
    assert text.startswith("---\n# Generated by `dec-tool pdf-authors`")
    # yamllint's default rules want list items indented under their key.
    assert "authors:\n  - id: b\n    commits: 2\n" in text
    assert yaml.safe_load(text) == {
        "repository": "eccenca/docs",
        "authors": [{"id": "b", "commits": 2}, {"id": "a", "commits": 1}],
    }
