---
name: 🚀 Documentation Request
description: Suggest an enhancement idea for the documentation.
title: "[Request]: "
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: Description
      description: >
        A clear and concise description of what the problem is.
         Ex. I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the documentation you'd like to have.
      description: |
        A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Context
      description: |
        Add any other context or screenshots about the feature request here.
    validations:
      required: false

