"""Write the author list the imprint of the print edition prints.

The authors are the GitHub accounts that contributed to the documentation
repository, most commits first. Anonymous contributions - commits whose e-mail
maps to no GitHub account - bot accounts and software agents are not listed.

The list is committed as tools/pdf/authors.yml, so a PDF build stays offline
and reproducible, and a changed list shows up in review. Invoked by
`task pdf:authors`; GITHUB_TOKEN or GH_TOKEN is used when set.
"""
from __future__ import annotations

import json
import os
import re
import urllib.request
from pathlib import Path

import click
import yaml

REPOSITORY = "eccenca/documentation.eccenca.com"
AUTHORS_YML = Path("tools/pdf/authors.yml")
API = "https://api.github.com"
# Agents commit under ordinary accounts of type User, so they are named here.
AGENT = re.compile(r"claude|codex", re.IGNORECASE)


def select_authors(contributors: list[dict]) -> list[dict]:
    """The contributors the imprint lists, in its order: most commits first, ties by ID, case-insensitive."""
    people = [
        c for c in contributors
        if c.get("type") == "User" and c.get("login") and not AGENT.search(c["login"])
    ]
    people.sort(key=lambda c: (-int(c["contributions"]), c["login"].casefold()))
    return [{"id": c["login"], "commits": int(c["contributions"])} for c in people]


def next_page(link_header: str) -> str | None:
    """The `rel="next"` URL of a GitHub Link header, if there is one."""
    match = re.search(r'<([^>]+)>;\s*rel="next"', link_header)
    return match.group(1) if match else None


def fetch_contributors(repository: str, token: str | None) -> list[dict]:
    """Every contributor of a repository, following the API's pagination.

    Without `anon=1` the API leaves out contributions that map to no account.
    """
    url: str | None = f"{API}/repos/{repository}/contributors?per_page=100"
    contributors: list[dict] = []
    while url:
        request = urllib.request.Request(url, headers={"Accept": "application/vnd.github+json"})
        if token:
            request.add_header("Authorization", f"Bearer {token}")
        with urllib.request.urlopen(request, timeout=30) as response:
            contributors.extend(json.load(response))
            url = next_page(response.headers.get("Link", ""))
    return contributors


class IndentedDumper(yaml.SafeDumper):
    """Indents list items under their key, as the repository's yamllint rules require."""

    def increase_indent(self, flow: bool = False, indentless: bool = False) -> None:
        return super().increase_indent(flow, False)


def authors_yaml(repository: str, authors: list[dict]) -> str:
    """The committed file: a header naming its source, then the list in imprint order."""
    header = (
        "---\n"
        "# Generated by `dec-tool pdf-authors` from the GitHub contributors of\n"
        f"# {repository}. Do not edit - run `task pdf:authors`.\n"
    )
    body = yaml.dump(
        {"repository": repository, "authors": authors},
        Dumper=IndentedDumper, sort_keys=False, allow_unicode=True,
    )
    return header + body


@click.command(name="pdf-authors")
@click.option(
    "--repository",
    default=REPOSITORY,
    help="Which GitHub repository's contributors are the authors?",
    show_default=True,
)
@click.option(
    "--output-file", "-o",
    type=click.Path(exists=False, dir_okay=False, file_okay=True),
    default=str(AUTHORS_YML),
    help="Where to write the author list?",
    show_default=True,
)
def pdf_authors(repository: str, output_file: str) -> None:
    """Write the imprint's author list from the repository's GitHub contributors."""
    token = os.environ.get("GITHUB_TOKEN") or os.environ.get("GH_TOKEN")
    authors = select_authors(fetch_contributors(repository, token))
    if not authors:
        raise click.ClickException(f"no contributors found for {repository}")
    Path(output_file).write_text(authors_yaml(repository, authors), encoding="utf-8")
    print(f"{len(authors)} authors written to {output_file}")
